In [2]:
import pandas as pd

df = pd.read_csv("customer_shopping_behavior.csv")

In [3]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [5]:
df.describe()  # df.describe(include='all')

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [6]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [7]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

# filling null values of RR by each categories median value it belongs. exampls-if clothing RR is null ,
# it will be only filled with median of clothing RR (not whole RR's median).

In [8]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [9]:
# converting column names into snakecase
df.columns = df.columns.str.lower().str.replace(' ', '_')

In [10]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [11]:
df = df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [12]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [13]:
# create a column age_group
labels = ['Young Adult', 'Adult', 'Middle-aged', 'Senior']
df['age_group'] = pd.qcut(df['age'], q=4, labels=labels)
# qcut() divides the data into equal-sized groups based on percentiles, then assigns the labels accordingly.

In [14]:
df[['age', 'age_group']].head(10)

   age    age_group
0   55  Middle-aged
1   19  Young Adult
2   50  Middle-aged
3   21  Young Adult
4   45  Middle-aged
5   46  Middle-aged
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57  Middle-aged

In [15]:
# create column purchase_frequency_days

frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually': 365,
    'Every 3 Months': 90
}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [16]:
df[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                       14            Fortnightly
1                       14            Fortnightly
2                        7                 Weekly
3                        7                 Weekly
4                      365               Annually
5                        7                 Weekly
6                       90              Quarterly
7                        7                 Weekly
8                      365               Annually
9                       90              Quarterly

In [17]:
df[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [18]:
(df['discount_applied'] == df['promo_code_used']).all()

True

In [19]:
df = df.drop('promo_code_used', axis=1)

In [20]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')

In [21]:
# connect data to postgreSQL
!pip install psycopg2-binary sqlalchemy

Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp310-cp310-win_amd64.whl.metadata (5.1 kB)
Requirement already satisfied: sqlalchemy in c:\users\pulina\appdata\local\programs\python\python310\lib\site-packages (2.0.44)
Requirement already satisfied: greenlet>=1 in c:\users\pulina\appdata\local\programs\python\python310\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\pulina\appdata\local\programs\python\python310\lib\site-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp310-cp310-win_amd64.whl (2.7 MB)
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   ----------- ---------------------------- 0.8/2.7 MB 4.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.7 MB 4.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.7 MB 4.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.7 MB 4.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.7 MB 4.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.7 MB 4.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.7 MB 4.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.7 MB 4.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.7 MB 4.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.7 MB 4.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.7 MB 4.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.7 MB 4.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.7 MB 4.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.7 MB 4.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.7 MB 4.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.7 MB 4.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.7 MB 4.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.7 MB 4.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.7 MB 4.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.7 MB 4.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.7 MB 4.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.7 MB 4.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.7 MB 4.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.7 MB 4.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.7 MB 4.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.7 MB 4.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.7 MB 4.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.7 MB 4.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.7 MB 4.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.7 MB 4.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.7 MB 4.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.7 MB 4.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.7 MB 4.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.7 MB 4.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.7 MB 4.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.7 MB 4.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.7 MB 4.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.7 MB 4.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.7 MB 4.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.7 MB 4.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.7 MB 4.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.7 MB 4.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.7 MB 4.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.7 MB 4.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.7 MB 4.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.7 MB 4.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.7 MB 4.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.7 MB 4.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.7 MB 4.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.7 MB 4.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.7 MB 4.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.7 MB 4.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.7 MB 4.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.7 MB 4.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.7 MB 4.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.7 MB 4.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.7 MB 4.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.7 MB 4.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.7 MB 4.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.7 MB 4.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.7 MB 4.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.7 MB 4.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.7 MB 4.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.7 MB 4.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.7 MB 4.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.7 MB 4.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.7 MB 4.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.7 MB 4.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.7 MB 4.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.7 MB 4.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.7 MB 4.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.7 MB 4.2 MB/s eta 0:00:01
Resuming download psycopg2_binary-2.9.11-cp310-cp310-win_amd64.whl (1.3 MB/2.7 MB)
   ------------------- -------------------- 1.3/2.7 MB ? eta -:--:--
   ------------------- -------------------- 1.3/2.7 MB ? eta -:--:--
   --------------------------- ------------ 1.8/2.7 MB 1.4 MB/s eta 0:00:01
   ------------------------------ --------- 2.1/2.7 MB 1.7 MB/s eta 0:00:01
   ------------------------------ --------- 2.1/2.7 MB 1.7 MB/s eta 0:00:01
   ------------------------------ --------- 2.1/2.7 MB 1.7 MB/s eta 0:00:01
   ------------------------------ --------- 2.1/2.7 MB 1.7 MB/s eta 0:00:01
   ------------------------------ --------- 2.1/2.7 MB 1.7 MB/s eta 0:00:01
   ------------------------------ --------- 2.1/2.7 MB 1.7 MB/s eta 0:00:01
   ------------------------------ --------- 2.1/2.7 MB 1.7 MB/s eta 0:00:01
   ------------------------------ --------- 2.1/2.7 MB 1.7 MB/s eta 0:00:01
   ------------------------------ --------- 2.1/2.7 MB 1.7 MB/s eta 0:00:01
   ------------------------------ --------- 2.1/2.7 MB 1.7 MB/s eta 0:00:01
   ------------------------------ --------- 2.1/2.7 MB 1.7 MB/s eta 0:00:01
   ------------------------------ --------- 2.1/2.7 MB 1.7 MB/s eta 0:00:01
   ------------------------------ --------- 2.1/2.7 MB 1.7 MB/s eta 0:00:01
   ------------------------------ --------- 2.1/2.7 MB 1.7 MB/s eta 0:00:01
   ---------------------------------- ----- 2.4/2.7 MB 301.0 kB/s eta 0:00:02
   ---------------------------------- ----- 2.4/2.7 MB 301.0 kB/s eta 0:00:02
   ---------------------------------- ----- 2.4/2.7 MB 301.0 kB/s eta 0:00:02
   -------------------------------------- - 2.6/2.7 MB 311.9 kB/s eta 0:00:01
   -------------------------------------- - 2.6/2.7 MB 311.9 kB/s eta 0:00:01
   ---------------------------------------- 2.7/2.7 MB 314.0 kB/s  0:00:04
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11

WARNING: Connection timed out while downloading.
WARNING: Attempting to resume incomplete download (1.3 MB/2.7 MB, attempt 1)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [22]:
import subprocess
import sys

def setup_postgresql():
    try:
        # Install PostgreSQL
        subprocess.run(['sudo', 'apt-get', 'update'], check=True)
        subprocess.run(['sudo', 'apt-get', 'install', '-y', 'postgresql', 'postgresql-contrib'], check=True)

        # Start PostgreSQL
        subprocess.run(['sudo', 'service', 'postgresql', 'start'], check=True)

        # Setup user and database
        subprocess.run(['sudo', '-u', 'postgres', 'psql', '-c', "ALTER USER postgres WITH PASSWORD 'pulina123';"], check=True)
        subprocess.run(['sudo', '-u', 'postgres', 'psql', '-c', "CREATE DATABASE customer_behaviour;"], check=True)

        print("PostgreSQL setup complete!")
        return True
    except Exception as e:
        print(f"Setup failed: {e}")
        return False

# Run setup
setup_postgresql()

Setup failed: Command '['sudo', 'apt-get', 'update']' returned non-zero exit status 2147942405.

False

In [23]:
from sqlalchemy import create_engine

# Step 1: Connect to PostgreSQL
username = 'postgres'
password = 'pulina123'
host = 'localhost'
port = '5432'
database = 'customer_behaviour'

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

# Step 2: Load DataFrame into PostgreSQL
table_name = 'customer'
df.to_sql(table_name, engine, if_exists="replace", index=False, schema='public')

print(f"Data successfuly loaded into table '{table_name}' in database '{database}'")

Data successfuly loaded into table 'customer' in database 'customer_behaviour'

In [24]:
result = pd.read_sql('SELECT * FROM "customer" LIMIT 20', engine)
result

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Middle-aged,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young Adult,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle-aged,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Young Adult,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Middle-aged,365
5,6,46,Male,Sneakers,Footwear,20,Wyoming,M,White,Summer,2.9,Yes,Standard,Yes,14,Venmo,Weekly,Middle-aged,7
6,7,63,Male,Shirt,Clothing,85,Montana,M,Gray,Fall,3.2,Yes,Free Shipping,Yes,49,Cash,Quarterly,Senior,90
7,8,27,Male,Shorts,Clothing,34,Louisiana,L,Charcoal,Winter,3.2,Yes,Free Shipping,Yes,19,Credit Card,Weekly,Young Adult,7
8,9,26,Male,Coat,Outerwear,97,West Virginia,L,Silver,Summer,2.6,Yes,Express,Yes,8,Venmo,Annually,Young Adult,365
9,10,57,Male,Handbag,Accessories,31,Missouri,M,Pink,Spring,4.8,Yes,2-Day Shipping,Yes,4,Cash,Quarterly,Middle-aged,90
10,11,53,Male,Shoes,Footwear,34,Arkansas,L,Purple,Fall,4.1,Yes,Store Pickup,Yes,26,Bank Transfer,Bi-Weekly,Middle-aged,14
11,12,30,Male,Shorts,Clothing,68,Hawaii,S,Olive,Winter,4.9,Yes,Store Pickup,Yes,10,Bank Transfer,Fortnightly,Young Adult,14
12,13,61,Male,Coat,Outerwear,72,Delaware,M,Gold,Winter,4.5,Yes,Express,Yes,37,Venmo,Fortnightly,Senior,14
13,14,65,Male,Dress,Clothing,51,New Hampshire,M,Violet,Spring,4.7,Yes,Express,Yes,31,PayPal,Weekly,Senior,7
14,15,64,Male,Coat,Outerwear,53,New York,L,Teal,Winter,4.7,Yes,Free Shipping,Yes,34,Debit Card,Weekly,Senior,7
15,16,64,Male,Skirt,Clothing,81,Rhode Island,M,Teal,Winter,2.8,Yes,Store Pickup,Yes,8,PayPal,Monthly,Senior,30
16,17,25,Male,Sunglasses,Accessories,36,Alabama,S,Gray,Spring,4.1,Yes,Next Day Air,Yes,44,Debit Card,Bi-Weekly,Young Adult,14
17,18,53,Male,Dress,Clothing,38,Mississippi,XL,Lavender,Winter,4.7,Yes,2-Day Shipping,Yes,36,Venmo,Quarterly,Middle-aged,90
18,19,52,Male,Sweater,Clothing,48,Montana,S,Black,Summer,4.6,Yes,Free Shipping,Yes,17,Cash,Weekly,Middle-aged,7
19,20,66,Male,Pants,Clothing,90,Rhode Island,M,Green,Summer,3.3,Yes,Standard,Yes,46,Debit Card,Bi-Weekly,Senior,14